version: '3.6'
networks:
    wordpress:
services:
  db:
    container_name: db
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
    image: mysql:5.7
    networks:
      - wordpress
    ports:
      - 3307:3306
    restart: always
    volumes:
      - wordpress:/var/lib/mysql
  wordpress:
    container_name: web
    depends_on:
      - db
    environment:
      WORDPRESS_DB_NAME: database
      WORDPRESS_DB_PASSWORD: password
    image: wordpress:latest
    links:
      - db:mysql
    networks:
      - wordpress
    ports:
      - 8080:80
      - 8443:443
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
volumes:
    wordpress:
